### ISSUE TITLE
Missing assert card for Swedish(swe)?

### ISSUE THREAD

**Issue by hitchhicker** [facebookresearch/SONAR#10]
Hey!

Swedish is in the list of supported languages but the card is not found? Is it expected?

Thanks!

**Comment by avidale** [comment]
Here is the line with the `swe_Latn` code in the text encoder:
https://github.com/facebookresearch/SONAR/blob/main/sonar/store/cards/text_sonar_basic_encoder.yaml#L181

For speech, Swedish is not in the list (https://github.com/facebookresearch/SONAR/tree/main#speech-results), so apparently it is not supported yet.

**Comment by hitchhicker** [comment]
Thanks for the reply! But the speech encoder is present in this [list](https://github.com/facebookresearch/SONAR/tree/main#supported-languages-and-download-links) (see Available speech encoders). And the checkpoint is available there.
