### ISSUE TITLE
How to Finetune with X->English data?

### ISSUE THREAD

**Issue by King-Rafat** [facebookresearch/SONAR#24]
I have a dataset with audio in X language having corresponding English translations. Should I finetune the encoder to match the vector space of encoded English text, or should I finetune the decoder after freezing the X audio encoder parameters? 

Thank you for your response!

**Comment by avidale** [comment]
Hi @King-Rafat!
The existing vector space already matches over 200 languages well, so we expect it to work well with yet another language. Thus, the recommended setup is to finetune the encoder for the language X to match this space. In this case, the embeddings for the new language would be compatible with all existing and future SONAR encoders and decoders.

**Comment by King-Rafat** [comment]
Thank you @avidale! Great to know that matching the new language encoder vector space with any other encoder vector space, be it text or speech, will work!
