### ISSUE TITLE
SONAR installation issue on colab and kaggle

### ISSUE THREAD

**Issue by nitishpandey04** [facebookresearch/SONAR#49]
I am following the installation instructions given [here](https://github.com/facebookresearch/SONAR?tab=readme-ov-file#installing). But running `pip install sonar-space` is overwriting the specific pytorch implementation I have installed following the set of variants given [here](https://github.com/facebookresearch/fairseq2?tab=readme-ov-file#variants). 

That is the reason fairseq2 is not working afterwords I guess, because sonar-space is overwriting the pytorch version other than what is required according to the variants table of fairseq2. 

Please help, how to install SONAR in cloud notebooks like colab and kaggle?

**Comment by nitishpandey04** [comment]
Reproduce on Kaggle CPU notebook:

`pip install sonar-space`

Run imports:
`from sonar.inference_pipelines.text import TextToEmbeddingModelPipeline`
`from sonar.models.blaser.loader import load_blaser_model`

Throws error:
`No moduled named fairseq2`

Install fairseq2 on CPU:
`!pip install fairseq2 --extra-index-url https://fair.pkg.atmeta.com/fairseq2/whl/pt2.4.0/cpu`

Run imports again:
`from sonar.inference_pipelines.text import TextToEmbeddingModelPipeline`
`from sonar.models.blaser.loader import load_blaser_model`

Throws error:
`ImportError: cannot import name 'default_asset_store' from 'fairseq2.assets' (/opt/conda/lib/python3.10/site-packages/fairseq2/assets/__init__.py)`

how to resolve? I am following the recommended installation instructions given at github repos of [sonar](https://github.com/facebookresearch/SONAR?tab=readme-ov-file#installing) and [fairseq2](https://github.com/facebookresearch/fairseq2?tab=readme-ov-file#variants)

**Comment by t1waz** [comment]
pls resolve, same for me

**Comment by elbayadm** [comment]
Hi, @nitishpandey04, @t1waz!
As of https://github.com/facebookresearch/SONAR/pull/47 SONAR depends on fairseq2 0.3.0 rc1.
With Pytorch 2.5.1 and a variant from cpu, cu118, cu121 or cu124:
```sh
variant=cpu
pip install torch==2.5.1 --extra-index-url https://download.pytorch.org/whl/${variant}
pip install fairseq2==v0.3.0rc1 --pre --extra-index-url  https://fair.pkg.atmeta.com/fairseq2/whl/rc/pt2.5.1/${variant}
```
Then `pip install sonar-space`.

If you prefer another version of Pytorch, then I believe all of the versions in the HEAD section [here](https://github.com/facebookresearch/fairseq2?tab=readme-ov-file#variants) are available in 0.3.0 rc1; simply change to something like:
```
pip install torch==2.3.0 --extra-index-url https://download.pytorch.org/whl/cpu
pip install fairseq2==v0.3.0rc1 --pre --extra-index-url  https://fair.pkg.atmeta.com/fairseq2/whl/rc/pt2.3.0/cpu
```

**Comment by t1waz** [comment]
@elbayadm, just checked the CPU variant - it's working, thanks a lot for Your help

**Comment by nitishpandey04** [comment]
Hi @elbayadm
Thanks for your help. The second example you provided for torch version 2.3.0 is working on kaggle for CPU. 
But I want to run it on GPU as I have an HPC with 3 a40 gpus with `nvidia-smi` showing `CUDA Version:  12.2`. 

I am trying to run on GPU of Kaggle first, then I plan to replicate the process in my GPU with a different Cuda version. 

So, when I try on Kaggle GPU, this is happening - [kaggle notebook link](https://www.kaggle.com/code/nitishpandey04/sonar-encoders?scriptVersionId=213471797)

Can you please clarity how to install it on GPU variants?

And one more doubt is that the cuda variants mentioned in this are cu118, cu121 or cu124 only. Kaggle P100 has 12.6 and my HPC has 12.2. How do I install it for cuda versions other than 11.8, 12.1 and 12.4?

**Comment by elbayadm** [comment]
Hi @nitishpandey04!

It looks like it was an issue with reading the variable ${variant}, this works for me 
[kaggle notebook](https://www.kaggle.com/code/redgns/sonar-encoders) 

PyTorch binaries ship with their own CUDA runtime, so you shouldn't worry about your machine's nvcc version as long as your GPU is compatible with the variant you select.  In your case, A40 GPU is compatible with CUDA version 11.x and above.
It's recommended to choose the latest CUDA version available.

**Comment by nitishpandey04** [comment]
Thanks @elbayadm 
The solution you provided is working for GPU.
