### ISSUE TITLE
`fairseq2` installation issue for `sonar-space` for GPU

### ISSUE THREAD

**Issue by nitishpandey04** [facebookresearch/SONAR#50]
Hi,

This is a follow up on this closed issue - https://github.com/facebookresearch/SONAR/issues/49

I am not able to reopen the issue so I am creating a new issue. Here's the follow up comment I made regarding the installation of fairseq2 on GPU - https://github.com/facebookresearch/SONAR/issues/49#issuecomment-2547689824

Can you resolve this for me please?

**Comment by elbayadm** [comment]
Re-opened #49 and closing this one.
