### ISSUE TITLE
embedding -> text pipeline

### ISSUE THREAD

**Issue by ezekielbarnett** [facebookresearch/SONAR#9]
Thanks for your amazing work on this project.
Curious if you plan to create a simple wrapper for an embedding to text model pipeline? Basically a decoder only to leverage precomputed embeddings to translate into a variety of languages, rather than having to re-create the embeddings using the text2text pipelines over and over again.

Thanks!

**Comment by avidale** [comment]
This is going to be fixed by https://github.com/facebookresearch/SONAR/pull/15.
